### ISSUE TITLE
Add content to README.md file

### ISSUE THREAD

**Issue by dev-darrell** [GADS-MobileEdu-22/Schoolbox365#1]
Add information to the README file describing the app and explaining its purpose.

**Comment by SciSaif** [comment]
I would like to work on this but I don't know what the app is about

**Comment by dev-darrell** [comment]
Hello @SciSaif, thanks for your interest in our project! However, this project is not open-source as it's only for members of the Mobile-Edu-22 team from the Google Africa Developer Scholarship program.
Thanks for your understanding and I hope you find another great project to work on!

**Comment by dev-darrell** [comment]
This has been solved in commit 5da3dc5
