### ISSUE TITLE
Implementing Swiping for the Onboarding screen Items

### ISSUE THREAD

**Issue by Dablaze-ufc** [GADS-MobileEdu-22/Schoolbox365#3]
We need to implement swiping for the onboarding items using viewPager 2.

Here is the design to be followed: https://bit.ly/3dOnTGs

These searches can help with getting the dot indicators: https://bit.ly/2INBKkR and https://bit.ly/3dI08Q5

![On boarding screen one](https://user-images.githubusercontent.com/52836046/96605789-8488b400-12ee-11eb-9fea-e7377c4ed083.jpg)
![On boarding screen two](https://user-images.githubusercontent.com/52836046/96605800-8783a480-12ee-11eb-9527-913e42516f02.png)
![On boarding screen three](https://user-images.githubusercontent.com/52836046/96605799-86eb0e00-12ee-11eb-96d9-249f2f06bd2a.png)

**Comment by dev-darrell** [comment]
I want to work on this.
