### ISSUE TITLE
Add the message for 2nd onboarding screen to app resources

### ISSUE THREAD

**Issue by dev-darrell** [GADS-MobileEdu-22/Schoolbox365#5]
The title and message of the 2nd onboarding screen are shown in the design below.
They should be added as string resources in the app.

![Onboarding screen two](https://user-images.githubusercontent.com/52300159/96632336-71d2a700-130f-11eb-8c2b-49478b482d1f.png)

**Comment by SciSaif** [comment]
can I work on it?

**Comment by dev-darrell** [comment]
Hi @SciSaif. I sent a reply to your comment under issue #1
